# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.10

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - azureml-dataprep[fuse,pandas]==1.3.5
- scikit-learn=0.21.2
- joblib=0.13.2
- numpy=1.16.6
- pandas=0.24.2
- matplotlib=3.0.2
- seaborn=0.9.0

-f https://download.pytorch.org/whl/torch_stable.html
- Flask==1.1.1
- gunicorn==19.9.0
- itsdangerous==1.1.0
- Jinja2==2.10.1
- MarkupSafe==1.1.1
- Werkzeug==0.15.5
- scipy>=0.15.1
- scikit-learn==0.22.1
- torch==1.6.0+cpu
- fastai==1.0.61


